AnimationPointers:
	table_width 2, AnimationPointers
 dw BulbasaurAnimation
 dw CyndaquilAnimation
 dw QuilavaAnimation
 dw TyphlosionAnimation
 dw HtyphlosionAnimation
 dw RowletAnimation
 dw DartrixAnimation
 dw DecidueyeAnimation
 dw HdecidueyeAnimation
 dw OshawottAnimation
 dw DewottAnimation
 dw SamurottAnimation
 dw HsamurottAnimation
 dw ButterfreeAnimation
 dw BeedrillAnimation
 dw PidgeyAnimation
 dw PidgeottoAnimation
 dw PidgeotAnimation
 dw EkansAnimation
 dw ArbokAnimation
 dw PikachuAnimation
 dw RaichuAnimation
 dw NidorinaAnimation
 dw NidoqueenAnimation
 dw NidorinoAnimation
 dw NidokingAnimation
 dw ClefairyAnimation
 dw ClefableAnimation
 dw VulpixAnimation
 dw NinetalesAnimation
 dw JigglypuffAnimation
 dw WigglytuffAnimation
 dw ZubatAnimation
 dw GolbatAnimation
 dw CrobatAnimation
 dw GloomAnimation
 dw VileplumeAnimation
 dw BellossomAnimation
 dw ParasAnimation
 dw ParasectAnimation
 dw VenonatAnimation
 dw VenomothAnimation
 dw DiglettAnimation
 dw DugtrioAnimation
 dw MeowthAnimation
 dw PersianAnimation
 dw MankeyAnimation
 dw PrimeapeAnimation
 dw GrowlitheAnimation
 dw ArcanineAnimation
 dw HarcanineAnimation
 dw PoliwagAnimation
 dw PoliwhirlAnimation
 dw PoliwrathAnimation
 dw PolitoedAnimation
 dw AbraAnimation
 dw KadabraAnimation
 dw AlakazamAnimation
 dw MachopAnimation
 dw MachokeAnimation
 dw MachampAnimation
 dw WeepinbellAnimation
 dw VictreebelAnimation
 dw TentacruelAnimation
 dw GeodudeAnimation
 dw GravelerAnimation
 dw GolemAnimation
 dw PonytaAnimation
 dw RapidashAnimation
 dw SlowpokeAnimation
 dw SlowbroAnimation
 dw SlowkingAnimation
 dw MagnemiteAnimation
 dw MagnetonAnimation
 dw MagnezoneAnimation
 dw Farfetch_DAnimation
 dw GrimerAnimation
 dw MukAnimation
 dw CloysterAnimation
 dw GastlyAnimation
 dw HaunterAnimation
 dw GengarAnimation
 dw OnixAnimation
 dw SteelixAnimation
 dw VoltorbAnimation
 dw ElectrodeAnimation
 dw HelectrodeAnimation
 dw ExeggcuteAnimation
 dw ExeggutorAnimation
 dw HitmonleeAnimation
 dw HitmonchanAnimation
 dw HitmontopAnimation
 dw WeezingAnimation
 dw MrmimeAnimation
 dw RhyhornAnimation
 dw RhydonAnimation
 dw RhyperiorAnimation
 dw ChanseyAnimation
 dw BlisseyAnimation
 dw TangelaAnimation
 dw TangrowthAnimation
 dw KangaskhanAnimation
 dw SeadraAnimation
 dw KingdraAnimation
 dw StaryuAnimation
 dw StarmieAnimation
 dw ScytherAnimation
 dw ScizorAnimation
 dw KleavorAnimation
 dw JynxAnimation
 dw ElectabuzzAnimation
 dw ElectivireAnimation
 dw MagmarAnimation
 dw MagmortarAnimation
 dw PinsirAnimation
 dw TaurosAnimation
 dw MagikarpAnimation
 dw GyaradosAnimation
 dw LaprasAnimation
 dw EeveeAnimation
 dw VaporeonAnimation
 dw JolteonAnimation
 dw FlareonAnimation
 dw EspeonAnimation
 dw UmbreonAnimation
 dw LeafeonAnimation
 dw GlaceonAnimation
 dw SylveonAnimation
 dw PorygonAnimation
 dw Porygon2Animation
 dw Porygon_ZAnimation
 dw SnorlaxAnimation
 dw ChikoritaAnimation
 dw BayleefAnimation
 dw MeganiumAnimation
 dw TotodileAnimation
 dw CroconawAnimation
 dw FeraligatrAnimation
 dw FurretAnimation
 dw LedianAnimation
 dw AriadosAnimation
 dw ChinchouAnimation
 dw LanturnAnimation
 dw TogeticAnimation
 dw TogekissAnimation
 dw NatuAnimation
 dw XatuAnimation
 dw MareepAnimation
 dw FlaaffyAnimation
 dw AmpharosAnimation
 dw MarillAnimation
 dw AzumarillAnimation
 dw SudowoodoAnimation
 dw SkiploomAnimation
 dw JumpluffAnimation
 dw SunfloraAnimation
 dw WooperAnimation
 dw QuagsireAnimation
 dw MurkrowAnimation
 dw HonchkrowAnimation
 dw MisdreavusAnimation
 dw MismagiusAnimation
 dw YanmaAnimation
 dw YanmegaAnimation
 dw UnownAnimation
 dw GirafarigAnimation
 dw PinecoAnimation
 dw ForretressAnimation
 dw DunsparceAnimation
 dw GligarAnimation
 dw GliscorAnimation
 dw SnubbullAnimation
 dw GranbullAnimation
 dw QwilfishAnimation
 dw OverqwilAnimation
 dw ShuckleAnimation
 dw HeracrossAnimation
 dw SneaselAnimation
 dw WeavileAnimation
 dw SneaslerAnimation
 dw TeddiursaAnimation
 dw UrsaringAnimation
 dw UrsalunaAnimation
 dw MagcargoAnimation
 dw PiloswineAnimation
 dw MamoswineAnimation
 dw CorsolaAnimation
 dw OctilleryAnimation
 dw MantineAnimation
 dw SkarmoryAnimation
 dw HoundourAnimation
 dw HoundoomAnimation
 dw DonphanAnimation
 dw StantlerAnimation
 dw WyrdeerAnimation
 dw MiltankAnimation
 dw GrotleAnimation
 dw TorterraAnimation
 dw MonfernoAnimation
 dw InfernapeAnimation
 dw PrinplupAnimation
 dw EmpoleonAnimation
 dw StaraviaAnimation
 dw StaraptorAnimation
 dw LuxioAnimation
 dw LuxrayAnimation
 dw RoseliaAnimation
 dw RoseradeAnimation
 dw RampardosAnimation
 dw BastiodonAnimation
 dw VespiquenAnimation
 dw AmbipomAnimation
 dw DrifblimAnimation
 dw LopunnyAnimation
 dw SkuntankAnimation
 dw BronzorAnimation
 dw BronzongAnimation
 dw SpiritombAnimation
 dw GabiteAnimation
 dw GarchompAnimation
 dw LucarioAnimation
 dw HippowdonAnimation
 dw DrapionAnimation
 dw ToxicroakAnimation
 dw SnoverAnimation
 dw AbomasnowAnimation
 dw DusclopsAnimation
 dw DusknoirAnimation
 dw FroslassAnimation
 dw RotomAnimation
 dw HavaluggAnimation
 dw BasculegionAnimation
 dw HbraviaryAnimation
 dw KirliaAnimation
 dw GardevoirAnimation
 dw GalladeAnimation
 dw HsliggooAnimation
 dw HgoodraAnimation
 dw HzoroarkAnimation
 dw DratiniAnimation
 dw DragonairAnimation
 dw DragoniteAnimation
 dw LarvitarAnimation
 dw PupitarAnimation
 dw TyranitarAnimation
 dw RaikouAnimation
 dw EnteiAnimation
 dw SuicuneAnimation
 dw HeatranAnimation
 dw LugiaAnimation
 dw Ho_OhAnimation
 dw CelebiAnimation
	assert_table_length NUM_POKEMON

 dw EggAnimation

 dw UnownBAnimation
 dw UnownCAnimation
 dw UnownDAnimation
 dw UnownEAnimation
 dw UnownFAnimation
 dw UnownGAnimation
 dw UnownHAnimation
 dw UnownIAnimation
 dw UnownJAnimation
 dw UnownKAnimation
 dw UnownLAnimation
 dw UnownMAnimation
 dw UnownNAnimation
 dw UnownOAnimation
 dw UnownPAnimation
 dw UnownQAnimation
 dw UnownRAnimation
 dw UnownSAnimation
 dw UnownTAnimation
 dw UnownUAnimation
 dw UnownVAnimation
 dw UnownWAnimation
 dw UnownXAnimation
 dw UnownYAnimation
 dw UnownZAnimation
 dw UnownExclamationAnimation
 dw UnownQuestionAnimation

	assert_table_length NUM_UNIQUE_POKEMON
