AnimationExtraPointers:
	table_width 2, AnimationExtraPointers
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw HtyphlosionAnimationExtra
	dw RowletAnimationExtra
	dw DartrixAnimationExtra
	dw DecidueyeAnimationExtra
	dw HdecidueyeAnimationExtra
	dw OshawottAnimationExtra
	dw DewottAnimationExtra
	dw SamurottAnimationExtra
	dw HsamurottAnimationExtra
	dw ButterfreeAnimationExtra
	dw BeedrillAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw EkansAnimationExtra
	dw ArbokAnimationExtra
	dw PikachuAnimationExtra
	dw RaichuAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw VulpixAnimationExtra
	dw NinetalesAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw CrobatAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw BellossomAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw DiglettAnimationExtra
	dw DugtrioAnimationExtra
	dw MeowthAnimationExtra
	dw PersianAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw HarcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw PolitoedAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw SlowkingAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw MagnezoneAnimationExtra
	dw Farfetch_DAnimationExtra
	dw GrimerAnimationExtra
	dw MukAnimationExtra
	dw CloysterAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw SteelixAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw HelectrodeAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw HitmontopAnimationExtra
	dw WeezingAnimationExtra
	dw MrmimeAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw RhyperiorAnimationExtra
	dw ChanseyAnimationExtra
	dw BlisseyAnimationExtra
	dw TangelaAnimationExtra
	dw TangrowthAnimationExtra
	dw KangaskhanAnimationExtra
	dw SeadraAnimationExtra
	dw KingdraAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw ScytherAnimationExtra
	dw ScizorAnimationExtra
	dw KleavorAnimationExtra
	dw JynxAnimationExtra
	dw ElectabuzzAnimationExtra
	dw ElectivireAnimationExtra
	dw MagmarAnimationExtra
	dw MagmortarAnimationExtra
	dw PinsirAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpAnimationExtra
	dw GyaradosAnimationExtra
	dw LaprasAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw SylveonAnimationExtra
	dw PorygonAnimationExtra
	dw Porygon2AnimationExtra
	dw Porygon_ZAnimationExtra
	dw SnorlaxAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw FurretAnimationExtra
	dw LedianAnimationExtra
	dw AriadosAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw TogeticAnimationExtra
	dw TogekissAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw SkiploomAnimationExtra
	dw JumpluffAnimationExtra
	dw SunfloraAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw MurkrowAnimationExtra
	dw HonchkrowAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw UnownAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw GliscorAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishAnimationExtra
	dw OverqwilAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw WeavileAnimationExtra
	dw SneaslerAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw UrsalunaAnimationExtra
	dw MagcargoAnimationExtra
	dw PiloswineAnimationExtra
	dw MamoswineAnimationExtra
	dw CorsolaAnimationExtra
	dw OctilleryAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw DonphanAnimationExtra
	dw StantlerAnimationExtra
	dw WyrdeerAnimationExtra
	dw MiltankAnimationExtra
	dw GrotleAnimationExtra
	dw TorterraAnimationExtra
	dw MonfernoAnimationExtra
	dw InfernapeAnimationExtra
	dw PrinplupAnimationExtra
	dw EmpoleonAnimationExtra
	dw StaraviaAnimationExtra
	dw StaraptorAnimationExtra
	dw LuxioAnimationExtra
	dw LuxrayAnimationExtra
	dw RoseliaAnimationExtra
	dw RoseradeAnimationExtra
	dw RampardosAnimationExtra
	dw BastiodonAnimationExtra
	dw VespiquenAnimationExtra
	dw AmbipomAnimationExtra
	dw DrifblimAnimationExtra
	dw LopunnyAnimationExtra
	dw SkuntankAnimationExtra
	dw BronzorAnimationExtra
	dw BronzongAnimationExtra
	dw SpiritombAnimationExtra
	dw GabiteAnimationExtra
	dw GarchompAnimationExtra
	dw LucarioAnimationExtra
	dw HippowdonAnimationExtra
	dw DrapionAnimationExtra
	dw ToxicroakAnimationExtra
	dw SnoverAnimationExtra
	dw AbomasnowAnimationExtra
	dw DusclopsAnimationExtra
	dw DusknoirAnimationExtra
	dw FroslassAnimationExtra
	dw RotomAnimationExtra
	dw HavaluggAnimationExtra
	dw BasculegionAnimationExtra
	dw HbraviaryAnimationExtra
	dw KirliaAnimationExtra
	dw GardevoirAnimationExtra
	dw GalladeAnimationExtra
	dw HsliggooAnimationExtra
	dw HgoodraAnimationExtra
	dw HzoroarkAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw HeatranAnimationExtra
	dw LugiaAnimationExtra
	dw Ho_OhAnimationExtra
	dw CelebiAnimationExtra
	assert_table_length NUM_POKEMON

	dw EggAnimationExtra

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	assert_table_length NUM_UNIQUE_POKEMON
