FramesPointers:
	table_width 2, FramesPointers
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw HtyphlosionFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw HdecidueyeFrames
	dw OshawottFrames
	dw DewottFrames
	dw SamurottFrames
	dw HsamurottFrames
	dw ButterfreeFrames
	dw BeedrillFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw EkansFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw GloomFrames
	dw VileplumeFrames
	dw BellossomFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw HarcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw PolitoedFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw SlowkingFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw Farfetch_DFrames
	dw GrimerFrames
	dw MukFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw SteelixFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw HelectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw HitmontopFrames
	dw WeezingFrames
	dw MrmimeFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw RhyperiorFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw KangaskhanFrames
	dw SeadraFrames
	dw KingdraFrames
	dw StaryuFrames
	dw StarmieFrames
	dw ScytherFrames
	dw ScizorFrames
	dw KleavorFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw ElectivireFrames
	dw MagmarFrames
	dw MagmortarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw Porygon_ZFrames
	dw SnorlaxFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw FurretFrames
	dw LedianFrames
	dw AriadosFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw TogeticFrames
	dw TogekissFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw SunfloraFrames
	dw WooperFrames
	dw QuagsireFrames
	dw MurkrowFrames
	dw HonchkrowFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw UnownFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw GliscorFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw OverqwilFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw SneaslerFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw UrsalunaFrames
	dw MagcargoFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw CorsolaFrames
	dw OctilleryFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw DonphanFrames
	dw StantlerFrames
	dw WyrdeerFrames
	dw MiltankFrames
	dw GrotleFrames
	dw TorterraFrames
	dw MonfernoFrames
	dw InfernapeFrames
	dw PrinplupFrames
	dw EmpoleonFrames
	dw StaraviaFrames
	dw StaraptorFrames
	dw LuxioFrames
	dw LuxrayFrames
	dw RoseliaFrames
	dw RoseradeFrames
	dw RampardosFrames
	dw BastiodonFrames
	dw VespiquenFrames
	dw AmbipomFrames
	dw DrifblimFrames
	dw LopunnyFrames
	dw SkuntankFrames
	dw BronzorFrames
	dw BronzongFrames
	dw SpiritombFrames
	dw GabiteFrames
	dw GarchompFrames
	dw LucarioFrames
	dw HippowdonFrames
	dw DrapionFrames
	dw ToxicroakFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw DusclopsFrames
	dw DusknoirFrames
	dw FroslassFrames
	dw RotomFrames
	dw HavaluggFrames
	dw BasculegionFrames
	dw HbraviaryFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw HsliggooFrames
	dw HgoodraFrames
	dw HzoroarkFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw HeatranFrames
	dw LugiaFrames
	dw Ho_OhFrames
	dw CelebiFrames

	assert_table_length NUM_POKEMON

	dw EggFrames

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames
;	assert_table_length NUM_UNIQUE_POKEMON
