# -*- coding: utf-8 -*-
"""
Created on Wed Jan 10 10:32:04 2024
@author: dwg11
"""
import pandas as pd
import os
path = 'C:/Users/dwg11/PLC_Polished/'
os.chdir(path)
#produces a spreadsheet with all the species data
path001 =  "data/pokemon/base_stats/cyndaquil.asm"
path002 =  "data/pokemon/base_stats/quilava.asm"
path003 =  "data/pokemon/base_stats/typhlosion.asm"
path004 =  "data/pokemon/base_stats/htyphlosion.asm" 
path005 =  "data/pokemon/base_stats/rowlet.asm" 
path006 =  "data/pokemon/base_stats/dartrix.asm" 
path007 =  "data/pokemon/base_stats/decidueye.asm" 
path008 =  "data/pokemon/base_stats/hdecidueye.asm" 
path009 =  "data/pokemon/base_stats/oshawott.asm" 
path010 =  "data/pokemon/base_stats/dewott.asm" 
path011 =  "data/pokemon/base_stats/samurott.asm" 
path012 =  "data/pokemon/base_stats/hsamurott.asm" 
path013 =  "data/pokemon/base_stats/butterfree.asm"
path014 =  "data/pokemon/base_stats/beedrill.asm"
path015 =  "data/pokemon/base_stats/pidgey.asm"
path016 =  "data/pokemon/base_stats/pidgeotto.asm"
path017 =  "data/pokemon/base_stats/pidgeot.asm"
path018 =  "data/pokemon/base_stats/ekans.asm"
path019 =  "data/pokemon/base_stats/arbok.asm"
path020 =  "data/pokemon/base_stats/pikachu.asm"
path021 =  "data/pokemon/base_stats/raichu.asm"
path022 =  "data/pokemon/base_stats/nidorina.asm"
path023 =  "data/pokemon/base_stats/nidoqueen.asm"
path024 =  "data/pokemon/base_stats/nidorino.asm"
path025 =  "data/pokemon/base_stats/nidoking.asm"
path026 =  "data/pokemon/base_stats/clefairy.asm"
path027 =  "data/pokemon/base_stats/clefable.asm"
path028 =  "data/pokemon/base_stats/vulpix.asm"
path029 =  "data/pokemon/base_stats/ninetales.asm"
path030 =  "data/pokemon/base_stats/jigglypuff.asm"
path031 =  "data/pokemon/base_stats/wigglytuff.asm"
path032 =  "data/pokemon/base_stats/zubat.asm"
path033 =  "data/pokemon/base_stats/golbat.asm"
path034 =  "data/pokemon/base_stats/crobat.asm"
path035 =  "data/pokemon/base_stats/gloom.asm"
path036 =  "data/pokemon/base_stats/vileplume.asm"
path037 =  "data/pokemon/base_stats/bellossom.asm"
path038 =  "data/pokemon/base_stats/paras.asm"
path039 =  "data/pokemon/base_stats/parasect.asm"
path040 =  "data/pokemon/base_stats/venonat.asm"
path041 =  "data/pokemon/base_stats/venomoth.asm"
path042 =  "data/pokemon/base_stats/diglett.asm"
path043 =  "data/pokemon/base_stats/dugtrio.asm"
path044 =  "data/pokemon/base_stats/meowth.asm"
path045 =  "data/pokemon/base_stats/persian.asm"
path046 =  "data/pokemon/base_stats/mankey.asm"
path047 =  "data/pokemon/base_stats/primeape.asm"
path048 =  "data/pokemon/base_stats/growlithe.asm"
path049 =  "data/pokemon/base_stats/arcanine.asm"
path050 =  "data/pokemon/base_stats/harcanine.asm"
path051 =  "data/pokemon/base_stats/poliwag.asm"
path052 =  "data/pokemon/base_stats/poliwhirl.asm"
path053 =  "data/pokemon/base_stats/poliwrath.asm"
path054 =  "data/pokemon/base_stats/politoed.asm"
path055 =  "data/pokemon/base_stats/abra.asm"
path056 =  "data/pokemon/base_stats/kadabra.asm"
path057 =  "data/pokemon/base_stats/alakazam.asm"
path058 =  "data/pokemon/base_stats/machop.asm"
path059 =  "data/pokemon/base_stats/machoke.asm"
path060 =  "data/pokemon/base_stats/machamp.asm"
path061 =  "data/pokemon/base_stats/weepinbell.asm"
path062 =  "data/pokemon/base_stats/victreebel.asm"
path063 =  "data/pokemon/base_stats/tentacruel.asm"
path064 =  "data/pokemon/base_stats/geodude.asm"
path065 =  "data/pokemon/base_stats/graveler.asm"
path066 =  "data/pokemon/base_stats/golem.asm"
path067 =  "data/pokemon/base_stats/ponyta.asm"
path068 =  "data/pokemon/base_stats/rapidash.asm"
path069 =  "data/pokemon/base_stats/slowpoke.asm"
path070 =  "data/pokemon/base_stats/slowbro.asm"
path071 =  "data/pokemon/base_stats/slowking.asm"
path072 =  "data/pokemon/base_stats/magnemite.asm"
path073 =  "data/pokemon/base_stats/magneton.asm"
path074 =  "data/pokemon/base_stats/magnezone.asm"
path075 =  "data/pokemon/base_stats/farfetch_d.asm"
path076 =  "data/pokemon/base_stats/grimer.asm"
path077 =  "data/pokemon/base_stats/muk.asm"
path078 =  "data/pokemon/base_stats/cloyster.asm"
path079 =  "data/pokemon/base_stats/gastly.asm"
path080 =  "data/pokemon/base_stats/haunter.asm"
path081 =  "data/pokemon/base_stats/gengar.asm"
path082 =  "data/pokemon/base_stats/onix.asm"
path083 =  "data/pokemon/base_stats/steelix.asm"
path084 =  "data/pokemon/base_stats/voltorb.asm"
path085 =  "data/pokemon/base_stats/electrode.asm"
path086 =  "data/pokemon/base_stats/helectrode.asm"
path087 =  "data/pokemon/base_stats/exeggcute.asm"
path088 =  "data/pokemon/base_stats/exeggutor.asm"
path089 =  "data/pokemon/base_stats/hitmonlee.asm"
path090 =  "data/pokemon/base_stats/hitmonchan.asm"
path091 =  "data/pokemon/base_stats/hitmontop.asm"
path092 =  "data/pokemon/base_stats/weezing.asm"
path093 =  "data/pokemon/base_stats/mrmime.asm"
path094 =  "data/pokemon/base_stats/rhyhorn.asm"
path095 =  "data/pokemon/base_stats/rhydon.asm"
path096 =  "data/pokemon/base_stats/rhyperior.asm"
path097 =  "data/pokemon/base_stats/chansey.asm"
path098 =  "data/pokemon/base_stats/blissey.asm"
path099 =  "data/pokemon/base_stats/tangela.asm"
path100 =  "data/pokemon/base_stats/tangrowth.asm"
path101 =  "data/pokemon/base_stats/kangaskhan.asm"
path102 =  "data/pokemon/base_stats/seadra.asm"
path103 =  "data/pokemon/base_stats/kingdra.asm"
path104 =  "data/pokemon/base_stats/staryu.asm"
path105 =  "data/pokemon/base_stats/starmie.asm"
path106 =  "data/pokemon/base_stats/scyther.asm"
path107 =  "data/pokemon/base_stats/scizor.asm"
path108 =  "data/pokemon/base_stats/kleavor.asm"
path109 =  "data/pokemon/base_stats/jynx.asm"
path110 =  "data/pokemon/base_stats/electabuzz.asm"
path111 =  "data/pokemon/base_stats/electivire.asm"
path112 =  "data/pokemon/base_stats/magmar.asm"
path113 =  "data/pokemon/base_stats/magmortar.asm"
path114 =  "data/pokemon/base_stats/pinsir.asm"
path115 =  "data/pokemon/base_stats/tauros.asm"
path116 =  "data/pokemon/base_stats/magikarp.asm"
path117 =  "data/pokemon/base_stats/gyarados.asm"
path118 =  "data/pokemon/base_stats/lapras.asm"
path119 =  "data/pokemon/base_stats/eevee.asm"
path120 =  "data/pokemon/base_stats/vaporeon.asm"
path121 =  "data/pokemon/base_stats/jolteon.asm"
path122 =  "data/pokemon/base_stats/flareon.asm"
path123 =  "data/pokemon/base_stats/espeon.asm"
path124 =  "data/pokemon/base_stats/umbreon.asm"
path125 =  "data/pokemon/base_stats/leafeon.asm"
path126 =  "data/pokemon/base_stats/glaceon.asm"
path127 =  "data/pokemon/base_stats/sylveon.asm"
path128 =  "data/pokemon/base_stats/porygon.asm"
path129 =  "data/pokemon/base_stats/porygon2.asm"
path130 =  "data/pokemon/base_stats/porygon_z.asm"
path131 =  "data/pokemon/base_stats/snorlax.asm"
path132 =  "data/pokemon/base_stats/chikorita.asm"
path133 =  "data/pokemon/base_stats/bayleef.asm"
path134 =  "data/pokemon/base_stats/meganium.asm"
path135 =  "data/pokemon/base_stats/totodile.asm"
path136 =  "data/pokemon/base_stats/croconaw.asm"
path137 =  "data/pokemon/base_stats/feraligatr.asm"
path138 =  "data/pokemon/base_stats/furret.asm"
path139 =  "data/pokemon/base_stats/ledian.asm"
path140 =  "data/pokemon/base_stats/ariados.asm"
path141 =  "data/pokemon/base_stats/chinchou.asm"
path142 =  "data/pokemon/base_stats/lanturn.asm"
path143 =  "data/pokemon/base_stats/togetic.asm"
path144 =  "data/pokemon/base_stats/togekiss.asm"
path145 =  "data/pokemon/base_stats/natu.asm"
path146 =  "data/pokemon/base_stats/xatu.asm"
path147 =  "data/pokemon/base_stats/mareep.asm"
path148 =  "data/pokemon/base_stats/flaaffy.asm"
path149 =  "data/pokemon/base_stats/ampharos.asm"
path150 =  "data/pokemon/base_stats/marill.asm"
path151 =  "data/pokemon/base_stats/azumarill.asm"
path152 =  "data/pokemon/base_stats/sudowoodo.asm"
path153 =  "data/pokemon/base_stats/skiploom.asm"
path154 =  "data/pokemon/base_stats/jumpluff.asm"
path155 =  "data/pokemon/base_stats/sunflora.asm"
path156 =  "data/pokemon/base_stats/wooper.asm"
path157 =  "data/pokemon/base_stats/quagsire.asm"
path158 =  "data/pokemon/base_stats/murkrow.asm"
path159 =  "data/pokemon/base_stats/honchkrow.asm"
path160 =  "data/pokemon/base_stats/misdreavus.asm"
path161 =  "data/pokemon/base_stats/mismagius.asm"
path162 =  "data/pokemon/base_stats/yanma.asm"
path163 =  "data/pokemon/base_stats/yanmega.asm"
path164 =  "data/pokemon/base_stats/unown.asm"
path165 =  "data/pokemon/base_stats/girafarig.asm"
path166 =  "data/pokemon/base_stats/pineco.asm"
path167 =  "data/pokemon/base_stats/forretress.asm"
path168 =  "data/pokemon/base_stats/dunsparce.asm"
path169 =  "data/pokemon/base_stats/gligar.asm"
path170 =  "data/pokemon/base_stats/gliscor.asm"
path171 =  "data/pokemon/base_stats/snubbull.asm"
path172 =  "data/pokemon/base_stats/granbull.asm"
path173 =  "data/pokemon/base_stats/qwilfish.asm"
path174 =  "data/pokemon/base_stats/overqwil.asm"
path175 =  "data/pokemon/base_stats/shuckle.asm"
path176 =  "data/pokemon/base_stats/heracross.asm"
path177 =  "data/pokemon/base_stats/sneasel.asm"
path178 =  "data/pokemon/base_stats/weavile.asm"
path179 =  "data/pokemon/base_stats/sneasler.asm"
path180 =  "data/pokemon/base_stats/teddiursa.asm"
path181 =  "data/pokemon/base_stats/ursaring.asm"
path182 =  "data/pokemon/base_stats/ursaluna.asm"
path183 =  "data/pokemon/base_stats/magcargo.asm"
path184 =  "data/pokemon/base_stats/piloswine.asm"
path185 =  "data/pokemon/base_stats/mamoswine.asm"
path186 =  "data/pokemon/base_stats/corsola.asm"
path187 =  "data/pokemon/base_stats/octillery.asm"
path188 =  "data/pokemon/base_stats/mantine.asm"
path189 =  "data/pokemon/base_stats/skarmory.asm"
path190 =  "data/pokemon/base_stats/houndour.asm"
path191 =  "data/pokemon/base_stats/houndoom.asm"
path192 =  "data/pokemon/base_stats/donphan.asm"
path193 =  "data/pokemon/base_stats/stantler.asm"
path194 =  "data/pokemon/base_stats/wyrdeer.asm" 
path195 =  "data/pokemon/base_stats/miltank.asm"
path196 =  "data/pokemon/base_stats/grotle.asm" 
path197 =  "data/pokemon/base_stats/torterra.asm" 
path198 =  "data/pokemon/base_stats/monferno.asm" 
path199 =  "data/pokemon/base_stats/infernape.asm" 
path200 =  "data/pokemon/base_stats/prinplup.asm" 
path201 =  "data/pokemon/base_stats/empoleon.asm" 
path202 =  "data/pokemon/base_stats/staravia.asm" 
path203 =  "data/pokemon/base_stats/staraptor.asm" 
path204 =  "data/pokemon/base_stats/luxio.asm" 
path205 =  "data/pokemon/base_stats/luxray.asm" 
path206 =  "data/pokemon/base_stats/roselia.asm" 
path207 =  "data/pokemon/base_stats/roserade.asm" 
path208 =  "data/pokemon/base_stats/rampardos.asm" 
path209 =  "data/pokemon/base_stats/bastiodon.asm" 
path210 =  "data/pokemon/base_stats/vespiquen.asm" 
path211 =  "data/pokemon/base_stats/ambipom.asm" 
path212 =  "data/pokemon/base_stats/drifblim.asm" 
path213 =  "data/pokemon/base_stats/lopunny.asm" 
path214 =  "data/pokemon/base_stats/skuntank.asm" 
path215 =  "data/pokemon/base_stats/bronzor.asm" 
path216 =  "data/pokemon/base_stats/bronzong.asm" 
path217 =  "data/pokemon/base_stats/spiritomb.asm" 
path218 =  "data/pokemon/base_stats/gabite.asm" 
path219 =  "data/pokemon/base_stats/garchomp.asm" 
path220 =  "data/pokemon/base_stats/lucario.asm" 
path221 =  "data/pokemon/base_stats/hippowdon.asm" 
path222 =  "data/pokemon/base_stats/drapion.asm" 
path223 =  "data/pokemon/base_stats/toxicroak.asm" 
path224 =  "data/pokemon/base_stats/snover.asm" 
path225 =  "data/pokemon/base_stats/abomasnow.asm" 
path226 =  "data/pokemon/base_stats/dusclops.asm" 
path227 =  "data/pokemon/base_stats/dusknoir.asm" 
path228 =  "data/pokemon/base_stats/froslass.asm" 
path229 =  "data/pokemon/base_stats/rotom.asm" 
path230 =  "data/pokemon/base_stats/havalugg.asm" 
path231 =  "data/pokemon/base_stats/basculegion.asm" 
path232 =  "data/pokemon/base_stats/hbraviary.asm" 
path233 =  "data/pokemon/base_stats/kirlia.asm" 
path234 =  "data/pokemon/base_stats/gardevoir.asm" 
path235 =  "data/pokemon/base_stats/gallade.asm" 
path236 =  "data/pokemon/base_stats/hsliggoo.asm" 
path237 =  "data/pokemon/base_stats/hgoodra.asm" 
path238 =  "data/pokemon/base_stats/hzoroark.asm" 
path239 =  "data/pokemon/base_stats/dratini.asm"
path240 =  "data/pokemon/base_stats/dragonair.asm"
path241 =  "data/pokemon/base_stats/dragonite.asm"
path242 =  "data/pokemon/base_stats/larvitar.asm"
path243 =  "data/pokemon/base_stats/pupitar.asm"
path244 =  "data/pokemon/base_stats/tyranitar.asm"
path245 =  "data/pokemon/base_stats/raikou.asm"
path246 =  "data/pokemon/base_stats/entei.asm"
path247 =  "data/pokemon/base_stats/suicune.asm"
path248 =  "data/pokemon/base_stats/heatran.asm" 
path249 =  "data/pokemon/base_stats/lugia.asm"
path250 =  "data/pokemon/base_stats/ho_oh.asm"
path251 =  "data/pokemon/base_stats/celebi.asm"

def check_formatting(files):
    # Read the contents of the first file
    with open(files[0], 'r') as f:
        reference_lines = f.readlines()

    # Compare the contents of the other files with the first one
    for file in files[1:]:
        with open(file, 'r') as f:
            lines = f.readlines()

        # Check if the number of lines is the same
        if len(lines) != len(reference_lines): #reference lines has 20 lines
            print(f"File '{file}' has a different number of lines.")
            return False

        # Check line by line for differences
       #for i, line in enumerate(lines):
       #    if line != reference_lines[i]:
       #        print(f"File '{file}' has different content at line {i+1}.")
       #        return False

    print("All files have the same formatting.")
    return True

# Replace 'file1.txt', 'file2.txt', ... with your file names
file_list = [path001, path002, path003, path004, path005, path006, path007, path008, path009, path010, path011, path012, path013, path014, path015, path016, path017, path018, path019, path020, path021, path022, path023, path024, path025, path026, path027, path028, path029, path030, path031, path032, path033, path034, path035, path036, path037, path038, path039, path040, path041, path042, path043, path044, path045, path046, path047, path048, path049, path050, path051, path052, path053, path054, path055, path056, path057, path058, path059, path060, path061, path062, path063, path064, path065, path066, path067, path068, path069, path070, path071, path072, path073, path074, path075, path076, path077, path078, path079, path080, path081, path082, path083, path084, path085, path086, path087, path088, path089, path090, path091, path092, path093, path094, path095, path096, path097, path098, path099, path100, path101, path102, path103, path104, path105, path106, path107, path108, path109, path110, path111, path112, path113, path114, path115, path116, path117, path118, path119, path120, path121, path122, path123, path124, path125, path126, path127, path128, path129, path130, path131, path132, path133, path134, path135, path136, path137, path138, path139, path140, path141, path142, path143, path144, path145, path146, path147, path148, path149, path150, path151, path152, path153, path154, path155, path156, path157, path158, path159, path160, path161, path162, path163, path164, path165, path166, path167, path168, path169, path170, path171, path172, path173, path174, path175, path176, path177, path178, path179, path180, path181, path182, path183, path184, path185, path186, path187, path188, path189, path190, path191, path192, path193, path194, path195, path196, path197, path198, path199, path200, path201, path202, path203, path204, path205, path206, path207, path208, path209, path210, path211, path212, path213, path214, path215, path216, path217, path218, path219, path220, path221, path222, path223, path224, path225, path226, path227, path228, path229, path230, path231, path232, path233, path234, path235, path236, path237, path238, path239, path240, path241, path242, path243, path244, path245, path246, path247, path248, path249, path250, path251]

check_formatting(file_list) #checks that all the files have what they need


#writes all of the pokemon data
def write_files_to_text(file_list, output_file):
    with open(output_file, 'w') as combined_file:
        for file_name in file_list:
            try:
                with open(file_name, 'r') as file:
                    combined_file.write(f"--- Contents of {file_name} ---\n")
                    combined_file.write(file.read())
                    combined_file.write("\n\n")
            except FileNotFoundError:
                print(f"File '{file_name}' not found.")

output_text_file = 'PKMN_BST_DATA.txt'  # Replace with the output file name

write_files_to_text(file_list, output_text_file)



